spring.application.name=quiz
spring.datasource.url= DATABASE URL

spring.datasource.username= DATABASE NAME 
spring.datasource.password= DATABASE PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

BREVO_API_KEY=YOUR_BREVO_API_KEY
spring.mvc.hiddenmethod.filter.enabled=true
server.error.whitelabel.enabled=false


app.upload.dir=uploads
